name: build guile-dsv with guile 2.2

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install guile-2.2 guile-2.2-libs guile-library
        
      - name: Checkout repository 
        uses: actions/checkout@v2

      - name: Run tests
        run: make check

